include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_new: false
    unnecessary_this: false
    prefer_null_aware_operators: false
    unnecessary_string_interpolations: false
